name: HA Automation REST API
version: "0.1.11"
slug: ha_automation_api
description: Expose Home Assistant automations and scripts through a secure REST API.
url: "https://github.com/runshotgun/HA-Automation-API"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
homeassistant_api: true
apparmor: false
ports:
  8099/tcp: 8099
map:
  - config:rw
options:
  api_key: ""
  allow_list: true
  allow_read: true
  allow_search: true
  allow_edit: false
  allow_delete: false
  allowed_ips: []
  automations_file: /config/automations.yaml
  scripts_file: /config/scripts.yaml
  backup_keep: 10
schema:
  api_key: password
  allow_list: bool
  allow_read: bool
  allow_search: bool
  allow_edit: bool
  allow_delete: bool
  allowed_ips:
    - str
  automations_file: str
  scripts_file: str
  backup_keep: int(1,100)
